### ISSUE TITLE
Update link does not show up in menu list

### ISSUE THREAD

**Issue by migmake** [familiar-studio/craft-menus#10]
I modified "Base documentaire" link but it does not show up in the list.
See screens 

![screen shot 2015-08-20 at 05 48 12](https://cloud.githubusercontent.com/assets/3531623/9386429/49474f3c-4710-11e5-94b1-91436e5050e2.jpg)

![screen shot 2015-08-20 at 05 48 07](https://cloud.githubusercontent.com/assets/3531623/9386428/493938f2-4710-11e5-8e07-394ebee0cbde.jpg)

**Comment by boborchard** [comment]
@migswd  Are you still having this issue? If so, let me know. If that update button is wrapped in an element using a class of `.buttons`, this Craft Menus plugin will hide it. I opened a PR against the plugin to remove that code: https://github.com/familiar-studio/craft-menus/pull/15

**Comment by migmake** [comment]
It must have been resolved ! So long ago dont know. ...
Lets close it :D
