### ISSUE TITLE
add field

### ISSUE THREAD

**Issue by moyger** [familiar-studio/craft-menus#20]
Is it possible to add a field to a menu item? For example, I may want to see a "description" of the menu. Thanks!

**Comment by keithmancuso** [comment]
Hey,

Sorry to say I haven been able to work on this plugin in a long while.  Luckily I shared a lot of the code with the team behind navee and I can say they have built out a much more complete vision of what I had in mind with this plugin.  It's really great you should try it out, a lot of the same ideas but added a ton more features!

https://github.com/fromtheoutfit/navee
