### ISSUE TITLE
Can't delete menu entries 

### ISSUE THREAD

**Issue by m9dfukc** [familiar-studio/craft-menus#5]
Hey,

I can't delete menu entries. A delete always results in 

```
Bad Request
POST param “categoryId” doesn’t exist.
```

As far as I remember it was working before. Could be that it broke during the last craft update?! Any suggestions ...

Using Craft  2.3.2640 and Menus 0.9.

**Comment by alvaxet** [comment]
Having the same issue, any update on this?

**Comment by alvaxet** [comment]
I've created a pull request with fix for this: https://github.com/familiar-studio/craft-menus/pull/8

**Comment by keithmancuso** [comment]
Fixed thanks to PR from @alvaxet.  

Thanks!
